// <auto-generated />
namespace NinjaDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IgnoreIsDirty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IgnoreIsDirty));
        
        string IMigrationMetadata.Id
        {
            get { return "201906301955387_Ignore-IsDirty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
